export enum LinksEnum {
  ADVERTISEMENT = 'ADVERTISEMENT',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  BLOG = 'BLOG',
  HOME_PAGE = 'HOME_PAGE',
  REFERENCES = 'REFERENCES',
  COMPANY_PAGE = 'COMPANY_PAGE',
  NEWS = 'NEWS',
  FREELANCE = 'FREELANCE',
  JOBS = 'JOBS',
}
